language: java
before_install:
  - chmod +x mvnw
deploy:
  api_key:
    secure: jDvp3tm6hbj74PtjYPyYIVmi9J/zOeLQLsWCG0wig53VquOH2RdHQ9o8e4Nae5xBh4125CbRkJUO/91myNGN92SfLSZgCF6U/us8KID7hBMEEALqSQLAFlN0qu8KnNCEh+2P7Gv86mERF6PQnUZ9utHYm1tW4gF2oJb+DUBVRmOElurZ4gjtmCvG4hXdVkn0eMus1gqiRNxU76qOQfP3CaELvZjQNqjMKCILcWuT/c6gSSXZmc/xSBBzfZGb3ERluXetojyzGM5n1s9ieqS1wn1D/KM9+yrrjkWVw9nLqJ/DtdfeDUkmFpgmK/chDOlcR4WaKZQtqgqAi1r1J1h4C1Zs3JVnoY+uP3fX6Jeov4C9LV6eVquxfFDBMWuxZlohltkoGz/DztScULV8xGP74xT0hvvlr9/DI2m8j4SgWINZ+pKk+JhkOOqu85NE8yifQ1Ygu/FjgFB3d/mdQtCtOymgzdaO8NuP81ppjHg0OtDgDNceAHJ0K+BDCvQuPNnDJhPrBj77UWIjAKkO32GngIt7+nk12yD6rTEiySxoKNZv1+F3YQVz9jaYUyw/z2eX7Dxhpi9ob2/bN30QtnRaOuGd5/KxKYC+Gyt3PbTEB0YDvKaiIDih5TzjSFe9JN3RkA//fTldKFNciD2gtGBkDOKNRpDpBImU0PHpWK74Foo=
