INSERT INTO currency_table VALUES (0, 'RUR', '₽') ON CONFLICT DO NOTHING;
INSERT INTO currency_table VALUES (1, 'USD', '$') ON CONFLICT DO NOTHING;
INSERT INTO currency_table VALUES (2, 'EUR', '€') ON CONFLICT DO NOTHING;